# https://doc.rust-lang.org/nightly/clippy/continuous_integration/github_actions.html
on:
  pull_request:
  push:
    branches:
      - main

name: Lints

# Make sure CI fails on all warnings, including Clippy lints
env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
